development:
  adapter: postgresql
  encoding: unicode
  database: fitch_slap_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: fitch_slap_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: fitch_slap_production
  pool: 5
  timeout: 5000
