development:
  adapter: postgresql
  encoding: unicode
  database: fitch_me_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: fitch_me_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: fitch_me_production
  pool: 5
  timeout: 5000
